# Generated by Django 3.2.7 on 2021-09-23 16:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210923_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bdate',
            field=models.DateField(blank=True, default=None, verbose_name='день рождения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 25, 16, 48, 7, 147944, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='возраст'),
        ),
    ]
