# Generated by Django 3.2.7 on 2021-09-23 16:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210923_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 25, 16, 51, 5, 610873, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bdate',
            field=models.DateField(blank=True, default='01.01.1998', verbose_name='день рождения'),
        ),
    ]
