# Generated by Django 3.2.7 on 2021-10-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baskets', '0002_basket_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
